packages:
  - apps/*
  - packages/*
  - packages/madea-blog-core/packages/*
  - integrations/*

ignoredBuiltDependencies:
  - keytar

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - sharp
  - unrs-resolver
