name: VS Code Extension Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-vscode-extension

      - name: Publish to VS Code Marketplace
        run: pnpm publish:extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX
        run: pnpm publish:extension:ovsx
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
