name: Web Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows/web-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows/web-tests.yml'
  workflow_dispatch:

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web
        run: pnpm build:web

      - name: Run unit tests
        run: pnpm test

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build & Install Yapi CLI
        run: |
          make build
          sudo cp ./bin/yapi /usr/local/bin/yapi
          yapi version

      - name: Run yapi integration tests
        uses: ./action  # jamierpond/yapi/action@main
        with:
          skip-install: true
          start: pnpm --filter web start --port 3000
          wait-on: http://localhost:3000/healthz
          command: yapi test ./apps/web/yapi -a -p 16

